Add new features
AlexanderSobko/java-filmorate pull request #2
Opened 2023-03-06 13:37 UTC by AlexanderSobko

2023-03-08 00:09 UTC, NikolaiDem requested changes

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      protected ResponseEntity<Object> handleValidationException(MethodArgumentNotValidException exception) {
В FilmController и UserController одинаковые обработчики исключений. Лучше вынести их обработку в отдельный класс @RestControllerAdvice ErrorHandler

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
>      public Film(String name, String description, LocalDate releaseDate, long duration) {
Конструктор лучше располагать сразу после полей класса.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    public static long currentId = 1L;
Генератор id лучше перенести в репозиторий.
И для User.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +            throw new NotExistsException("Пользователь", id);
Может быть не найден пользователь с id или friendId, а ошибка только с id.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +            throw new NotExistsException("Пользователь", id);
Может быть не найден пользователь с id или friendId, а ошибка только с id.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +            throw new NotExistsException("Пользователь", id);
Может быть не найден пользователь с id или friendId, а ошибка только с id.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +        if (userStorage.exists(id) && userStorage.exists(friendId)) {
Несколько раз встречается конструкция вида :
if (userStorage.exists(id) {
    throw new NotExistsException("Пользователь", id);
}
Можно это вынести в отдельный метод, чтобы избавиться от дублирования.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    Map<Long, Film> innerStorage;
private

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    Map<Long, User> innerStorage;
private

2023-03-08 00:09 UTC, NikolaiDem commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class  FilmorateApplicationTests {
Лишние изменения.

2023-03-08 00:09 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
> +            throw new NotExistsException("Фильм", filmId);
Несколько раз встречается конструкция вида :
if (filmStorage.exists(filmId) {
throw new NotExistsException("Фильм", filmId);
}
Можно это вынести в отдельный метод, чтобы избавиться от дублирования.

2023-03-08 05:39 UTC, AlexanderSobko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      protected ResponseEntity<Object> handleValidationException(MethodArgumentNotValidException exception) {
Самому не нравится, но при перемещении в RestResponseEntityExceptionHandler выбрасывает ошибку( 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'handlerExceptionResolver'

2023-03-08 23:54 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      protected ResponseEntity<Object> handleValidationException(MethodArgumentNotValidException exception) {
1 способ:
Переопределить метод 
    @Override
    protected ResponseEntity<Object> handleMethodArgumentNotValid(MethodArgumentNotValidException exception, HttpHeaders headers, HttpStatus status, WebRequest request) {
        return ResponseEntity.badRequest()
                .header("Content-Type", "application/json;charset=UTF-8")
                .body(exception.getBindingResult().getAllErrors());
    }
    
2 способ:
Не наследоваться от ResponseEntityExceptionHandler.

2023-03-08 23:59 UTC, NikolaiDem requested changes

2023-03-08 23:59 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
>  @Component
Component нужен для классов, инстансы (бины) которых будут управляться спрингом. А для класса модели это не нужно.
Аналогично для User.

2023-03-10 22:16 UTC, NikolaiDem approved these changes

2023-03-14 06:37 UTC, merged