feat: ad h2 db and other things according to the task list
AlexanderSobko/java-filmorate pull request #3
Opened 2023-03-18 19:43 UTC by AlexanderSobko

2023-03-19 10:37 UTC, AlexanderSobko commented
Как по мне тут ошибка в тестах, т.к. они пытабтся добавить лайк к фильму через DELETE запрос

2023-03-20 00:35 UTC, NikolaiDem requested changes
Сборку нужно починить.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/AbstractController.java
> +public abstract class AbstractController<E, S extends EntityService<?>> {
Какой профит дает абстрактный контроллер?

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/FilmService.java
>      public List<Film> getTopFilms(String count) {
Сделать сортировку фильмов на уровне sql запроса.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +        List<Integer> commonFriends = new ArrayList<>(userStorage.getFriends(id));
Сделать фильтрацию на уровне sql запроса, чтобы userStorage вернул сразу список друзей.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +                .map(this::get)
Проблема N+1 запроса, вернуть список друзей сразу из userStorage

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            linkMpa(id, entity.getMpa().getId());
mpa_id лучше хранить в таблице films, так как связь у них 1:1

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            entity.getGenres().forEach(genre -> linkGenre(id, genre.getId()));
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            deleteMpa(entity.getId(), film.getMpa().getId());
Так как таблицы film_mpas не будет, то достаточно заменить только mpa_id в films.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            entity.getGenres().forEach(genre -> linkGenre(entity.getId(), genre.getId()));
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.getGenres().forEach(genre -> deleteGenre(entity.getId(), genre.getId()));
Удалить можно сразу все по film_id

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        films.forEach(f -> {
Здесь возникает проблема "N+1 query". Одним запросом получены все N фильмов, и для каждого фильма нужно сделать еще по одному запросу (на получение жанров), то есть дополнительных N запросов. Как вариант снизить количество дополнительных запросов до одного - использовать
void query(String sql, RowCallbackHandler rch, @Nullable Object... args)
Где sql - запрос на получение всех жанров (то есть такая сджойненная таблица : filmId, genreId, genreName).  Пройти по всем строкам такой сджойненной таблицы, и для каждой строки сконструировать жанр и добавить его в соответствующий фильм. Для этого установку жанров лучше вынести в отдельный метод.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            f.setLikes(getLikes(f.getId()));
Лайки нужно получить одним запросом для всего списка фильмов.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            f.setGenres(getGenresByFilmId(f.getId()));
Жанры нужно получить одним запросом для всего списка фильмов.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String sql = "INSERT INTO film_likes (film_id,user_id) VALUES (?,?);";
Лучше merge into

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать unchecked исключения в бизнес логике - нехорошая практика.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        } catch (RuntimeException e) {
Перехватывать unchecked исключения в бизнес логике - нехорошая практика.

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Set<Integer> getLikes(int film_id);
Нужно ли выносить метод в интерфейс? Используется как служебный

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre save(Genre entity) {
Нарушается Interface Segregation Principle из SOLID

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    public Mpa save(Mpa entity) {
Нарушается Interface Segregation Principle из SOLID

2023-03-20 00:35 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
Удалять все объекты не нужно.

2023-03-20 09:35 UTC, AlexanderSobko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/AbstractController.java
> +public abstract class AbstractController<E, S extends EntityService<?>> {
Да по сути никакого, я хотел написать в нем все дубли в лонике (все CRUD операции повторяются) + вынести validation exception hendler  в родителя, но столкнулся с тем что мне нужно было все модели привести к одному родителю,

2023-03-26 05:26 UTC, AlexanderSobko commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
Я их удаляю только чтобы пройти тесты на гите

2023-03-27 20:06 UTC, NikolaiDem requested changes

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +public class FilmController extends AbstractController<Film, FilmService> {
Так как профита никакого нет, то лучше удалить наследование.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/AbstractController.java
> +    protected ResponseEntity<Object> handleValidationException(MethodArgumentNotValidException exception) {
Перенести обработку исключений в отдельный класс, так как профита от абстрактного контроллера нет)

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      public ResponseEntity<List<Film>> getTopFilms(@RequestParam(required = false, defaultValue = "10") String count) {
"required" не нужен, если задано дефолтное значение

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    public ResponseEntity<Genre> save(Genre entity) {
save и update нарушают I из SOLID, класс реализует методы, которые не используются. Удалить наследование от AbstractController

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/MpaController.java
> +    public ResponseEntity<Mpa> save(Mpa entity) {
save и update нарушают I из SOLID, класс реализует методы, которые не используются. Удалить наследование от AbstractController

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController extends AbstractController<User, UserService> {
Так как профита никакого нет, то лучше удалить наследование.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/GenreService.java
> +    public Genre save(Genre entity) {
save и update нарушают I из SOLID, класс реализует методы, которые не используются. Реализовать интерфейс, в котором не будет лишних методов.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/MpaService.java
> +    public Mpa save(Mpa entity) {
save и update нарушают I из SOLID, класс реализует методы, которые не используются. Реализовать интерфейс, в котором не будет лишних методов.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/services/UserService.java
> +                .map(this::get)
Не исправлено, userStorage должен вернуть уже готовый список User-ов, чтобы потом N раз не обращаться к БД (this::get)

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            entity.getGenres().forEach(genre -> linkGenre(id, genre.getId()));
Не исправлено

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.getGenres().forEach(genre -> deleteGenre(entity.getId(), genre.getId()));
Не исправлено

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            entity.getGenres().forEach(genre -> linkGenre(entity.getId(), genre.getId()));
Не исправлено

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        films.forEach(f -> {
Не исправлено

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            f.setGenres(getGenresByFilmId(f.getId()));
Не исправлено

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            f.setGenres(getGenresByFilmId(f.getId()));
Жанры нужно получить одним запросом для всего списка фильмов.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            f.setLikes(getLikes(f.getId()));
Лайки нужно получить одним запросом для всего списка фильмов.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Set<Integer> getLikes(int film_id);
Не исправлено

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +    public Genre save(Genre entity) {
Не исправлено для save, delete и update

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    public Mpa save(Mpa entity) {
Не исправлено для save, delete и update

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        users.forEach(u -> u.setFriends(getFriends(u.getId())));
Друзей нужно получить одним запросом для всего списка пользователей.

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        String sql = "SELECT f.friend_id from (SELECT friend_id FROM friends WHERE user_id = ?) AS f\n" +
Избавиться от подзапросов, использовать джойны

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                .map(this::findById)
Проблема N+1 запроса, лучше использовать query(...) с RowMapper

2023-03-27 20:06 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
В чем проблема без их удаления?

2023-04-02 13:09 UTC, NikolaiDem approved these changes

2023-04-04 09:56 UTC, merged